FROM ubuntu
ENTRYPOINT ["/bin/bash"]
RUN apt-get update
RUN apt-get upgrade -y

# install some basic things
RUN apt-get install -y curl
RUN apt-get install -y wget
RUN apt-get install -y xclip
RUN apt-get install -y unzip
RUN apt-get install -y vim
RUN apt-get install -y sudo
RUN apt-get install -y jq
RUN apt-get install -y netcat
RUN apt-get install -y kafkacat
RUN echo alias kcat=kafkacat >>/root/.bashrc


# micro - favorite editor in containers
WORKDIR /usr/local/bin
RUN curl https://getmic.ro | bash
# install plugins
WORKDIR /root/.config/micro/plugins
# Install the file manager plugin, and keybinding Alt+T to activate
RUN wget https://github.com/NicolaiSoeborg/filemanager-plugin/archive/master.zip
RUN unzip master.zip
RUN rm master.zip
RUN mv filemanager-plugin-master filemanager
RUN echo '{"Alt-t": "command:tree"}' >/root/.config/micro/bindings.json
# Install comment plugin, so Alt+/ will comment/uncomment lines
RUN wget https://github.com/micro-editor/comment-plugin/archive/master.zip
RUN unzip master.zip
RUN rm master.zip
RUN mv comment-plugin-master comment
WORKDIR /root


# ibmcloud
RUN curl -sL https://ibm.biz/idt-installer | bash
RUN echo alias kc=kubectl >>/root/.bashrc
RUN ibmcloud plugin install at
RUN ibmcloud plugin install mr
RUN ibmcloud plugin install cbr

# Helm
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh
RUN rm get_helm.sh

# node:
RUN apt-get install -y nodejs
RUN apt-get install -y npm

# Z Shell
RUN apt-get install -y zsh
RUN wget https://raw.githubusercontent.com/randybertram/scratch/master/.zshrc


# # go:
# WORKDIR /root
# RUN wget https://golang.org/dl/go1.16.linux-amd64.tar.gz
# RUN tar -C /usr/local -xzf go1.16.linux-amd64.tar.gz
# RUN rm go1.16.linux-amd64.tar.gz
# RUN echo 'export PATH=$PATH:/usr/local/go/bin:/root/go/bin' >>/root/.zshrc
# # are the following all needed?
# RUN apt install go-bindata
# RUN go get golang.org/x/tools/cmd/goimports
# RUN go get -u github.com/jstemmer/go-junit-report
